name: Deploy Azure Data Factory Resources

on: # Trigger on push to the main branch
  push:
   branches:
    - test
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-adf:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Azure using service principal
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: Validate ARM Template
        run: |
            az deployment group validate \
              --resource-group test \
              --template-file ARMTemplateForFactory.json \
              --parameters ARMTemplateParametersForFactory.json

      # Deploy ADF pipelines and datasets
      - name: Deploy ADF Resources
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: test  # Replace with your resource group name
          dataFactoryName: sampletestuo8009  # ADF instance name from secret
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          armTemplateFile: ARMTemplateForFactory.json
          # Optional: Specify environment-specific configuration
          # additionalParameters: 'stage=deployment/config-prod.json'
          # Optional: Skip Az module installation to speed up
          # skipAzModuleInstallation: true
